### PR TITLE
Timestamp should also include milliseconds

### PR DESCRIPTION
**Pull request by gdoron**

### CODE REVIEW

**Comment by gdoron** [comment]
@kkamkou I hope this library is still being maintained.
Is it?

Thanks,
Doron

**Comment by kkamkou** [comment]
it is. thank you for the contribution.

**Comment by gdoron** [comment]
@kkamkou, cool. Thanks for merging so quick.
Can you please also push to NPM while at it?

**Comment by kkamkou** [comment]
Will do it tomorrow.

**Comment by gdoron** [comment]
@kkamkou while at it, if you don't mind.
I wonder what's the story behind `version: '1.1'` 
https://github.com/kkamkou/node-gelf-pro/blob/323f13fe3afc7d7afaa919b1ac0326f8be16e443/lib/gelf-pro.js#L80
And should be removed?

**Comment by kkamkou** [comment]
https://docs.graylog.org/en/3.2/pages/gelf.html

**Pull request merged**
