### PR TITLE
TCP socket reuse

### PR DESCRIPTION
**Pull request by npomfret**
TCP socket reuse

### CODE REVIEW

**Review by kkamkou — CHANGES_REQUESTED** [review]
Thank you for the contribution. Nice one. A number of clues:
1. working with an active socket requires advanced logic to handle multiple messages. For example: one send 10 messages, at message number 5 the socket has been lost. What should we do with the rest messages? Error them like in this pr? Or try to recover as this adapter provides a socket connection.
2. there is no clear logic how to keep the connection alive. In your case, the line 79-80 should be extended with `return this._instance(...)`.

Could we shift it into a separate adapter?

**Comment by npomfret** [comment]
did you incorporate this change?

**Comment by kkamkou** [comment]
@npomfret no I din't. There is [multiple](https://github.com/fdelayen/node-gelf-pro/commit/b52b4b6b1ff26772314b8673dd6fd724c0937caa) implementations of the same idea.
I can't add an incomplete solution into the final package. But we can always create a new adapter. Right now I don't have time for it.

**Comment by npomfret** [comment]
ok no problem.  I'll switch packages

**Pull request closed without merging**
